import {Dimensions} from 'react-native';
import {Colors} from './constants';
import {constants} from 'App/constants';

export default {
  cardContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    flexDirection: 'column',
  },
  coverContainer: {
    position: 'relative',
  },
  coverImage: {
    height: Dimensions.get('window').height * (1 / 5),
    width: Dimensions.get('window').width,
    resizeMode: 'contain',
    backgroundColor: constants.PURPLE,
    backgroundColor: 'black',
    overflow: 'hidden',
  },
  headerContainer: {
    alignItems: 'center',
  },
  scroll: {
    backgroundColor: constants.PURPLE,
    flex: 1,
    marginBottom: 55,
  },
  productRow: {
    marginTop: 15,
    marginLeft: 15,
    marginRight: 15,
    backgroundColor: 'rgba(255,255,255,.8)',
    borderRadius: 10,
    padding: 20,
    zIndex: 200,
  },
  mainViewStyle: {
    flex: 1,
    flexDirection: 'column',
    flexGrow: 1,
    backgroundColor: constants.PURPLE,
  },
  coverMetaContainer: {
    alignItems: 'flex-end',
    flex: 1,
    justifyContent: 'flex-end',
  },
  cluckfooter: {
    alignItems: 'center',
    backgroundColor: 'rgba(227, 100, 73, 0.7)',
    bottom: '35%',
    //flex: 1,
    flexDirection: 'row',
    height: 75,
    width: '20%',
    right: 0,
    position: 'absolute',
    right: 0,
    marginTop: 0,
    borderRadius: 10,
    zIndex: 100,
  },
  footer: {
    shadowOffset: {height: -5},
    shadowOpacity: 0.05,

    alignItems: 'center',
    zIndex: 400,
    backgroundColor: '#ff4733',
    //backgroundColor: '#e36449',
    bottom: 0,
    flex: 1,
    flexDirection: 'row',
    height: 65,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  buttonCluck: {
    alignItems: 'center',
    flex: 2,
    justifyContent: 'center',
  },
  buttonFooter: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  navigatorButton: {
    alignItems: 'flex-start',
    flex: 1,
    justifyContent: 'center',
  },
  navigatorText: {
    alignItems: 'flex-start',
    color: '#459ff3',
    fontSize: 16,
    fontWeight: 'bold',
    justifyContent: 'center',
  },
  borderCenter: {
    borderColor: '#FFA890',
    borderWidth: 0.5,
    height: 55,
  },
  textFooter: {
    alignItems: 'center',
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: constants.FONT,
  },
  priceText: {
    color: Colors.black,
    fontSize: 24,
    fontWeight: '400',
    letterSpacing: 1,
    marginBottom: 5,
  },
  detailText: {
    color: Colors.black,
    fontSize: 22,
    fontWeight: '600',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  subDetailText: {
    color: Colors.black,
    fontSize: 16,
    fontWeight: '100',
    letterSpacing: 0.5,
    lineHeight: 28,
  },
  descriptionText: {
    color: Colors.gray,
    fontSize: 16,
    fontWeight: '400',
    letterSpacing: 1,
    marginBottom: 4,
  },
  circleProfile: {
    height: 40,
    width: 40,
    borderRadius: 20,
    resizeMode: 'contain',
  },
};
